  const NATIVE_CHAT_TEXT_SELECTOR = [
    ".chat-markdown-part.rendered-markdown",
    ".chat-markdown-part.rendered-markdown p",
    ".chat-markdown-part.rendered-markdown li",
    ".chat-markdown-part.rendered-markdown blockquote",
    ".chat-markdown-part.rendered-markdown ol",
    ".chat-markdown-part.rendered-markdown ul",
    ".chat-markdown-part.rendered-markdown table",
    ".chat-markdown-part.rendered-markdown thead",
    ".chat-markdown-part.rendered-markdown tbody",
    ".chat-markdown-part.rendered-markdown tr",
    ".chat-markdown-part.rendered-markdown th",
    ".chat-markdown-part.rendered-markdown td",
    ".agent-session-title",
    ".agent-session-title-row",
    ".monaco-icon-name-container",
  ].join(",");
  const ANTIGRAVITY_CHAT_TEXT_SELECTOR = [
    "p",
    "li",
    "blockquote",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    ".whitespace-pre-wrap",
    "[class*='whitespace-pre-wrap']",
    "[dir='auto']",
    "[role='article'] p",
    "[role='article'] li",
    "[role='article'] blockquote",
    "div.text-size-chat.overflow-y-auto.p-2",
    "div.text-size-chat.overflow-auto.p-2",
  ].join(",");
  const GEMINI_CHAT_TEXT_SELECTOR = [
    ".history-item-text",
    ".history-item-text p",
    ".history-item-text li",
    ".history-item-text blockquote",
    ".history-item-text ol",
    ".history-item-text ul",
    ".history-item-text table",
    ".history-item-text thead",
    ".history-item-text tbody",
    ".history-item-text tr",
    ".history-item-text th",
    ".history-item-text td",
    ".mdc-evolution-chip__text-label",
    ".mat-mdc-chip-action-label",
  ].join(",");
  const CODE_LIKE_SELECTOR = "code,pre,kbd,.font-mono,[role='code'],.ProseMirror,.hljs,.monaco-editor,.monaco-tokenized-source,.monaco-keybinding,textarea,input,[contenteditable='true']";
